import = ["/home/sweglord227/.config/alacritty/themes/carbon_fox.toml"]

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
# size = 14.0

[font.normal]
family = "CozetteHiDpi"
# family = "Monospace"

[window]
dynamic_padding = true
opacity = 0.4
resize_increments = true
title = "Terminal"
