import = ["/home/sweglord227/.config/alacritty/themes/carbon_fox.toml"]

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 13

[font.normal]
family = "BigBlueTermPlus Nerd Font"
# family = "Monospace"

[window]
dynamic_padding = true
opacity = 0.6
resize_increments = true
title = "Terminal"
