import = ["/home/sweglord227/.config/alacritty/themes/carbon_fox.toml"]

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 16.0

[font.normal]
# family = "BigBlueTermPlus Nerd Font"
# family = "ComicShannsMonoNerdFontPropo"
family = "CozetteHiDpi"
# family = "Monospace"

[window]
dynamic_padding = true
opacity = 0.85
resize_increments = true
title = "Terminal"
