[theme]
        theme = "plain"
[icons]
        icons = "awesome6"
[icons.overrides]
        cpu = ""
        bat = [
		" ",
                " ",
                " ",
                " ",
                " ",
        ]

#[[block]]
#        block = "pacman"
#        interval = 60
#        error_interval = 30
#        format = "$icon$both"
#        format_singular = "$icon$both"
#        format_up_to_date = ""
#        critical_updates_regex = "(linux-lts|linux-zen)"
#        # aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
#        aur_command = "paru -Qua"

[[block]]
        block = "cpu"
        interval = 2
        format = " $icon $utilization $barchart "

[[block]]
        block = "temperature"
        interval = 0.5
        format = " $icon $average "

[[block]]
	block = "memory"
	interval = 2
	format = " $icon $mem_free.eng(w:3,u:B,p:Mi)/$mem_total.eng(u:B,p:Mi) "

[[block]]
        block = "battery"
        interval = 30
        format = " $icon $percentage $time "
        full_format = " $icon $percentage "
        missing_format = " $icon $percentage "
        empty_format = " $icon $percentage "
        not_charging_format = " $icon $percentage "
        driver = "upower"

[[block]]
        block = "time"
        interval = 1
        format = " $timestamp.datetime(f:'%T %d/%m/%y ') "

[[block]]
	block = "sound"
	step_width = 5
