if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
	#export LIBVA_DRIVER_NAME=nvidia
	#export GBM_BACKEND=nvidia-drm
	#export __GLX_VENDOR_LIBRARY_NAME=nvidia
	#export WLR_NO_HARDWARE_CURSORS=1
	#export WLR_RENDERER=vulkan [BREAKS FOR MEEEEEE]
	export MOZ_ENABLE_WAYLAND=1 # [REQUIRED: Firefox will break otherwise.]
	#export XDG_SESSION_TYPE=wayland # Probably dont need to set this manually
        QT_STYLE_OVERRIDE=Adwaita-Dark
	exec Hyprland
fi
