# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.config/oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#
# dst, alanpeabody, emotty, gnzh, geoffgarside
# xiong-chiamiov-plus, johnathan
ZSH_THEME="refined"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="false"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
zstyle ':omz:update' mode reminder      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 7

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
DISABLE_LS_COLORS="false"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="dd.mm.yyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
        git
        zsh-autosuggestions
        rust
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Lines configured by zsh-newuser-install
HISTFILE=~/.history
HISTSIZE=1000
SAVEHIST=10000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/sweglord227/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall


# Remove mode switching delay.
KEYTIMEOUT=5

# Change cursor shape for different vi modes.
# function zle-keymap-select {
#         if [[ ${KEYMAP} == vicmd ]] ||
#         [[ $1 = 'block' ]]; then
#                 echo -ne '\e[1 q'
#
#         elif [[ ${KEYMAP} == main ]] ||
#         [[ ${KEYMAP} == viins ]] ||
#         [[ ${KEYMAP} = '' ]] ||
#         [[ $1 = 'beam' ]]; then
#                 echo -ne '\e[5 q'
#         fi
# }
# zle -N zle-keymap-select
# # Use beam shape cursor on startup.
# echo -ne '\e[5 q'

# Fix unable to backspace after exiting vi mode
bindkey "^?" backward-delete-char


alias gamescope='gamescope -W 1920 -H 1080 -r 120 -S stretch --expose-wayland -e --rt -f'
alias vi='nvim'
alias vim='nvim'
alias pi='sudo pacman -S'
alias pu='sudo pacman -Syu'
alias pr='sudo pacman -R'
alias ls='eza -lh --git --icons=always'
alias grep='grep --color=auto'
alias fuck='sudo $(history -p !!)'
alias shit='shutdown now'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias ip='ip -c'
alias time='/usr/bin/time'
alias fetch='fastfetch'

alias c='cargo'

eval "$(zoxide init --cmd cd zsh)"

# PS1='\[\e[1;00m\]┌──\[\e[1;32m\][\u@\h]\[\e[1;00m\]─\[\e[1;37m\](\w)\n\[\e[1;00m\]└─\[\e[0;00m\]\$ '
